#!/usr/bin/env python3
"""
generate_skeleton.py — Generate a test class skeleton from a Risk Profile
(JSON output of classify_risk.py). Claude fills in the actual assertions
and arrange blocks — this script handles the boilerplate.

Usage:
    python generate_skeleton.py <risk_profile.json> [options]
    python generate_skeleton.py risk_profile.json
    python generate_skeleton.py risk_profile.json --lang php --out tests/Unit/PaymentServiceTest.php
    python generate_skeleton.py risk_profile.json --type feature

Can also run the full pipeline automatically:
    python generate_skeleton.py --pipeline app/Services/PaymentService.php
    python generate_skeleton.py --pipeline app/Services/PaymentService.php --out tests/Unit/PaymentServiceTest.php
"""

import json
import argparse
import subprocess
import sys
import tempfile
import re
from pathlib import Path
from datetime import datetime


# ─── Language config ──────────────────────────────────────────────────────────

SUPPORTED_LANGS = ["php", "python", "js"]

# Map source file extension to test language
EXT_TO_LANG = {
    ".php": "php",
    ".py": "python",
    ".js": "js",
    ".ts": "js",
    ".jsx": "js",
    ".tsx": "js",
}

# Map test type to PHPUnit base class
PHP_BASE_CLASSES = {
    "unit":        "Tests\\TestCase",
    "feature":     "Tests\\TestCase",
    "integration": "Tests\\TestCase",
}


# ─── PHP skeleton generator ───────────────────────────────────────────────────

def generate_php(profile: dict, test_type: str) -> str:
    class_name = profile["class_name"]
    fqn = profile.get("fqn", class_name)
    namespace_parts = fqn.split("\\")[:-1] if "\\" in fqn else []

    test_class = f"{class_name}Test"
    global_fakes = profile.get("global_fakes_needed", [])
    global_se = profile.get("global_side_effects", [])
    constructor_deps = profile.get("constructor_dependencies", [])
    methods = profile.get("methods", [])

    # Build test namespace
    if test_type == "unit":
        test_ns = "Tests\\Unit"
    elif test_type == "feature":
        test_ns = "Tests\\Feature"
    else:
        test_ns = "Tests\\Integration"

    # Guess output path
    if namespace_parts:
        sub = "\\".join(namespace_parts).replace("App\\", "")
        test_ns = f"{test_ns}\\{sub}"

    lines = []
    lines.append(f"<?php")
    lines.append(f"")
    lines.append(f"namespace {test_ns};")
    lines.append(f"")
    lines.append(f"use {fqn};")

    # Add fake imports based on side effects
    fake_imports = {
        "QUEUE":      "Illuminate\\Support\\Facades\\Queue",
        "EVENT":      "Illuminate\\Support\\Facades\\Event",
        "MAIL":       "Illuminate\\Support\\Facades\\Mail",
        "HTTP":       "Illuminate\\Support\\Facades\\Http",
        "CACHE":      "Illuminate\\Support\\Facades\\Cache",
        "FILESYSTEM": "Illuminate\\Support\\Facades\\Storage",
    }
    for se in global_se:
        if se in fake_imports:
            lines.append(f"use {fake_imports[se]};")

    # Traits
    needs_refresh_db = any(se in ("DB_WRITE", "DB_READ") for se in global_se)

    lines.append(f"use Tests\\TestCase;")
    if needs_refresh_db:
        lines.append(f"use Illuminate\\Foundation\\Testing\\RefreshDatabase;")
    lines.append(f"use PHPUnit\\Framework\\Attributes\\Test;")
    lines.append(f"")
    lines.append(f"/**")
    lines.append(f" * @generated by test-generator skill — {datetime.now().strftime('%Y-%m-%d')}")
    lines.append(f" * Risk Profile: {profile.get('class_tier', 'MEDIUM')} tier")
    lines.append(f" * TODO: Fill in arrange blocks and assertion details")
    lines.append(f" */")
    lines.append(f"class {test_class} extends TestCase")
    lines.append(f"{{")

    if needs_refresh_db:
        lines.append(f"    use RefreshDatabase;")
        lines.append(f"")

    # Properties for dependencies
    if constructor_deps:
        for dep in constructor_deps:
            short = dep.split("\\")[-1]
            prop = _to_camel(short)
            lines.append(f"    private {short} ${prop};")
        lines.append(f"")

    lines.append(f"    private {class_name} $sut;  // System Under Test")
    lines.append(f"")

    # setUp
    lines.append(f"    protected function setUp(): void")
    lines.append(f"    {{")
    lines.append(f"        parent::setUp();")
    lines.append(f"")

    # Fakes
    for se in global_se:
        fake_call = _fake_call_php(se)
        if fake_call:
            lines.append(f"        {fake_call}")

    lines.append(f"")

    # Instantiate dependencies
    if constructor_deps:
        for dep in constructor_deps:
            short = dep.split("\\")[-1]
            prop = _to_camel(short)
            lines.append(f"        $this->{prop} = $this->mock({short}::class);")
        lines.append(f"")
        deps_str = ", ".join(f"$this->{_to_camel(d.split(chr(92))[-1])}" for d in constructor_deps)
        lines.append(f"        $this->sut = new {class_name}({deps_str});")
    else:
        lines.append(f"        $this->sut = new {class_name}();")

    lines.append(f"    }}")
    lines.append(f"")

    # Test methods
    for method in methods:
        lines.extend(_php_method_tests(method, class_name))

    lines.append(f"}}")
    lines.append(f"")

    return "\n".join(lines)


def _fake_call_php(se_type: str) -> str:
    return {
        "QUEUE":      "Queue::fake();",
        "EVENT":      "Event::fake();",
        "MAIL":       "Mail::fake();",
        "HTTP":       "Http::fake();  // TODO: configure responses per test",
        "CACHE":      "// Cache uses in-memory driver in tests (config/testing)",
        "FILESYSTEM": "Storage::fake();",
    }.get(se_type, "")


def _php_method_tests(method: dict, class_name: str) -> list:
    name = method["name"]
    tier = method["complexity_tier"]
    branches = method.get("branches", [])
    side_effects = method.get("side_effects", [])
    preconditions = method.get("preconditions", [])
    checklist = method.get("test_checklist", [])

    lines = []
    lines.append(f"    // ─── {name}() — {tier} tier ───────────────────────────────")
    lines.append(f"")

    for item in checklist:
        # Parse method name from checklist item
        method_match = re.match(r"`(test_\w+)\(\)`", item)
        if not method_match:
            continue

        test_name = method_match.group(1)
        comment = item.split("—")[-1].strip() if "—" in item else ""

        lines.append(f"    #[Test]")
        lines.append(f"    public function {test_name}(): void")
        lines.append(f"    {{")
        lines.append(f"        // Arrange — {comment}")
        lines.append(f"        // TODO: set up state")
        lines.append(f"")
        lines.append(f"        // Act")
        lines.append(f"        // TODO: $result = $this->sut->{name}(...);")
        lines.append(f"")
        lines.append(f"        // Assert")
        _add_assert_hints_php(lines, item, side_effects)
        lines.append(f"    }}")
        lines.append(f"")

    return lines


def _add_assert_hints_php(lines: list, checklist_item: str, side_effects: list) -> None:
    item_lower = checklist_item.lower()

    if "dispatches_job" in item_lower or "queue" in item_lower:
        lines.append(f"        Queue::assertPushed(/* JobClass::class */);")
    elif "fires_event" in item_lower or "event" in item_lower:
        lines.append(f"        Event::assertDispatched(/* EventClass::class */);")
    elif "sends_mail" in item_lower or "mail" in item_lower:
        lines.append(f"        Mail::assertSent(/* MailableClass::class */);")
    elif "persists" in item_lower or "database" in item_lower:
        lines.append(f"        $this->assertDatabaseHas('table_name', [")
        lines.append(f"            // TODO: key => expected_value")
        lines.append(f"        ]);")
    elif "stores_file" in item_lower:
        lines.append(f"        Storage::assertExists('path/to/file');")
    elif "throws" in item_lower or "exception" in item_lower:
        lines.append(f"        $this->expectException(\\Exception::class);")
    elif "does_not_persist" in item_lower or "not_triggered" in item_lower:
        for se in side_effects:
            if se["type"] == "QUEUE":
                lines.append(f"        Queue::assertNothingPushed();")
            elif se["type"] == "EVENT":
                lines.append(f"        Event::assertNotDispatched(/* EventClass::class */);")
            elif se["type"] == "MAIL":
                lines.append(f"        Mail::assertNothingSent();")
    else:
        lines.append(f"        // TODO: $this->assertEquals(expected, $result);")


# ─── Python skeleton generator ────────────────────────────────────────────────

def generate_python(profile: dict, test_type: str) -> str:
    class_name = profile["class_name"]
    methods = profile.get("methods", [])
    global_se = profile.get("global_side_effects", [])
    constructor_deps = profile.get("constructor_dependencies", [])

    lines = []
    lines.append(f"\"\"\"")
    lines.append(f"Generated by test-generator skill — {datetime.now().strftime('%Y-%m-%d')}")
    lines.append(f"Risk Profile: {profile.get('class_tier', 'MEDIUM')} tier")
    lines.append(f"TODO: Fill in arrange blocks and assertion details")
    lines.append(f"\"\"\"")
    lines.append(f"")
    lines.append(f"import pytest")
    lines.append(f"from unittest.mock import MagicMock, patch")
    lines.append(f"# TODO: from your_module import {class_name}")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"class Test{class_name}:")
    lines.append(f"")
    lines.append(f"    @pytest.fixture(autouse=True)")
    lines.append(f"    def setup(self):")

    if constructor_deps:
        for dep in constructor_deps:
            prop = _to_snake(dep)
            lines.append(f"        self.{prop} = MagicMock()")
        deps_str = ", ".join(f"self.{_to_snake(d)}" for d in constructor_deps)
        lines.append(f"        self.sut = {class_name}({deps_str})")
    else:
        lines.append(f"        self.sut = {class_name}()")

    lines.append(f"")

    for method in methods:
        name = method["name"]
        tier = method["complexity_tier"]
        checklist = method.get("test_checklist", [])

        lines.append(f"    # ─── {name}() — {tier} tier")
        lines.append(f"")

        for item in checklist:
            method_match = re.match(r"`(test_\w+)\(\)`", item)
            if not method_match:
                continue
            test_name = method_match.group(1)
            comment = item.split("—")[-1].strip() if "—" in item else ""

            lines.append(f"    def {test_name}(self):")
            lines.append(f"        # Arrange — {comment}")
            lines.append(f"        # TODO: set up state")
            lines.append(f"")
            lines.append(f"        # Act")
            lines.append(f"        # TODO: result = self.sut.{name}(...)")
            lines.append(f"")
            lines.append(f"        # Assert")
            lines.append(f"        # TODO: assert result == expected")
            lines.append(f"")

    return "\n".join(lines)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _to_camel(s: str) -> str:
    return s[0].lower() + s[1:] if s else s


def _to_snake(s: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()


def _detect_lang_from_profile(profile: dict) -> str:
    file_path = profile.get("file", "")
    if file_path:
        ext = Path(file_path).suffix.lower()
        return EXT_TO_LANG.get(ext, "php")
    return "php"


# ─── Entry point ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a test class skeleton from a Risk Profile JSON."
    )
    parser.add_argument("risk_profile", nargs="?",
                        help="Risk Profile JSON from classify_risk.py --format json")
    parser.add_argument(
        "--pipeline", metavar="SOURCE_FILE",
        help="Auto-run parse_class.py + classify_risk.py on this file first"
    )
    parser.add_argument(
        "--lang", choices=SUPPORTED_LANGS, default=None,
        help="Target language (default: auto-detect from source file)"
    )
    parser.add_argument(
        "--type", choices=["unit", "feature", "integration"], default="unit",
        dest="test_type",
        help="Test type (default: unit)"
    )
    parser.add_argument("--out", default=None, help="Output file path")
    args = parser.parse_args()

    scripts_dir = Path(__file__).parent

    # Pipeline mode: parse + classify + generate
    if args.pipeline:
        source_file = args.pipeline

        with tempfile.NamedTemporaryFile(suffix=".json", delete=False, mode="w") as tf:
            parsed_tmp = tf.name
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False, mode="w") as tf:
            profile_tmp = tf.name

        # Determine which scripts dir to use
        classifier_scripts = scripts_dir.parent.parent / "test-risk-classifier" / "scripts"

        print(f"Parsing: {source_file}", file=sys.stderr)
        subprocess.run(
            [sys.executable, str(classifier_scripts / "parse_class.py"),
             source_file, "--out", parsed_tmp],
            check=True
        )
        print(f"Classifying risk...", file=sys.stderr)
        subprocess.run(
            [sys.executable, str(classifier_scripts / "classify_risk.py"),
             parsed_tmp, "--format", "json", "--out", profile_tmp],
            check=True
        )

        profile = json.loads(Path(profile_tmp).read_text())
        Path(parsed_tmp).unlink(missing_ok=True)
        Path(profile_tmp).unlink(missing_ok=True)

    elif args.risk_profile:
        profile = json.loads(Path(args.risk_profile).read_text())
    else:
        parser.print_help()
        sys.exit(1)

    lang = args.lang or _detect_lang_from_profile(profile)

    print(f"Generating {lang} skeleton for {profile['class_name']}...", file=sys.stderr)

    if lang == "php":
        output = generate_php(profile, args.test_type)
    elif lang == "python":
        output = generate_python(profile, args.test_type)
    else:
        print(f"Error: unsupported language '{lang}'", file=sys.stderr)
        sys.exit(1)

    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(output, encoding="utf-8")
        print(f"Skeleton → {args.out}", file=sys.stderr)
        print(f"", file=sys.stderr)
        print(f"Next step: Open the file and fill in the TODO sections.", file=sys.stderr)
        print(f"Run: php artisan test {args.out}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
